### ISSUE TITLE
Example of make_simlibs usage

### ISSUE THREAD

**Issue by Catarina-Alves** [LSSTDESC/OpSimSummary#310]
**Is your feature request related to a problem? Please describe.**
I wanted to run `make_simlibs.py` but it is hard to know how to use it. Even after using the help `python make_simlibs.py -h`, there are so many options that I am overwhelmed and I don't know what to do. I have also tried to go to the examples folder but that did not help.

**Describe the solution you'd like**
Writing an example of simple usage would be good. This can be done by adding an example notebook.

**Comment by rbiswas4** [comment]
Would you like to write the notebook?
